import os,json,zipfile
from html import escape
root=os.path.dirname(os.path.abspath(__file__));out=os.path.join(root,'Data_Engineering_Assessment_6_Abhishek_Sethi.docx');nb=json.load(open(os.path.join(root,'Assessment_6.ipynb'),encoding='utf-8'))
N='http://schemas.openxmlformats.org/wordprocessingml/2006/main';R='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
def x(s):return escape(str(s),quote=False)
def p(s='',st=None):return f'<w:p>{f"<w:pPr><w:pStyle w:val=\"{st}\"/></w:pPr>" if st else ""}<w:r><w:t xml:space="preserve">{x(s)}</w:t></w:r></w:p>'
def h(s,n=1):return p(s,f'Heading{n}')
def b(s):return f'<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>{x(s)}</w:t></w:r></w:p>'
def c(s):return ''.join(p(v or ' ','Code') for v in s.rstrip().splitlines())
def pg():return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'
def t(headers,rows,w=None):
 w=w or [3000]*len(headers)
 def z(v,width,hd=False):return f'<w:tc><w:tcPr><w:tcW w:w="{width}" w:type="dxa"/>{"<w:shd w:fill=\"D9EAF7\"/>" if hd else ""}</w:tcPr><w:p><w:r>{"<w:rPr><w:b/></w:rPr>" if hd else ""}<w:t xml:space="preserve">{x(v)}</w:t></w:r></w:p></w:tc>'
 return '<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/></w:tblPr><w:tr>'+''.join(z(v,w[i],1) for i,v in enumerate(headers))+'</w:tr>'+''.join('<w:tr>'+''.join(z(v,w[i]) for i,v in enumerate(row))+'</w:tr>' for row in rows)+'</w:tbl>'
q=[]
for tx,sz in [('DATA ENGINEERING','36'),('ASSESSMENT 6','32'),('PySpark Transaction Preparation and Output Formats','28')]:q.append(f'<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:before="280" w:after="280"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="{sz}"/></w:rPr><w:t>{tx}</w:t></w:r></w:p>')
q += [p('Practical Assessment Report'),t(['Report detail','Information'],[('Student name','Abhishek Sethi'),('Course / subject','Data Engineering'),('Institution','Not specified in supplied material'),('Academic year','Not specified in supplied material')],[3000,5500]),pg(),h('Table of Contents'),'<w:p><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText>TOC \\o "1-2" \\h \\z \\u</w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>Update this table in Microsoft Word (References → Update Table) to display page numbers.</w:t></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p>',pg()]
q += [h('1. Assignment Overview'),p('This assessment applies Spark DataFrame selection, filtering, renaming, type conversion, derived-price calculation, aggregation, and file output to a transaction dataset. It writes results in CSV and Parquet formats and reads the Parquet output again for verification.')]
q += [h('2. Aim'),p('To prepare transaction records with PySpark, apply business filters and aggregations, and store the processed results in CSV and Parquet formats.')]
q += [h('3. Problem Statement'),p('A transaction CSV must be imported into Spark, transformed into a more analysis-ready structure, inspected through business conditions, summarised by category, and persisted in reusable file formats.')]
q += [h('4. Objectives')]
for s in ['Read source.csv through Spark with header and schema inference.','Select fields and filter Electronics transactions.','Rename old_name, cast price, and derive a tax-inclusive final_price.','Apply completed/high-value, known-user, and region/priority conditions.','Count transactions by category.','Write output to CSV and Parquet.','Read the Parquet output again to verify successful storage.']:q.append(b(s))
q += [h('5. Requirements'),t(['Requirement','Supplied material'],[('Source','data/source.csv.'),('Implementation','Assessment_6.ipynb.'),('Processing framework','PySpark SparkSession and pyspark.sql.functions.'),('Outputs','output/csv_output and output/parquet_output.'),('Evidence','Assessment_6.pdf and Assessment_6_merged.pdf exported artefacts; generated CSV/Parquet files and _SUCCESS markers.')],[2600,5900])]
q += [h('6. Tools and Technologies'),t(['Area','Technology actually used'],[('Language','Python'),('Processing','Apache Spark / PySpark DataFrame API'),('Functions','pyspark.sql.functions.col and round'),('Formats','CSV and Apache Parquet'),('Execution environment','Jupyter Notebook')],[2800,5700])]
q += [h('7. Dataset/Input Information'),t(['Aspect','Details'],[('Dataset','source.csv'),('Source location','Assessment 6/data/source.csv'),('Format','CSV with header.'),('Record count','5 transactions.'),('Important fields','product_id, category, price, stock, old_name, base_price, user_id, status, amount, region, priority.'),('Characteristics','Contains one missing user_id; three Electronics records; completed/pending status values; and regional/priority attributes.')],[2800,5700])]
q += [h('8. Data Schema'),t(['Field','Use in the implementation'],[('product_id, category','Selected and used for product/category processing.'),('price, base_price','price is cast to double; base_price is used to calculate final_price.'),('old_name / new_name','old_name is renamed to new_name.'),('user_id','Used to filter known-user records.'),('status, amount','Used to identify completed high-value orders.'),('region, priority','Used in the North-or-High filter.'),('final_price','Derived as base_price × 1.18, rounded to two decimals.')],[2800,5700])]
q += [h('9. Technical Concepts')]
for s in ['SparkSession creation and CSV ingestion with inferred schema.','Column selection, filter conditions, Boolean AND/OR predicates, and null filtering.','Schema evolution using withColumnRenamed and withColumn/cast.','Derived values using Spark expressions and round.','groupBy/count aggregation.','CSV and Parquet data persistence.','Read-back validation of the Parquet output.']:q.append(b(s))
q += [h('10. Overall Workflow'),t(['Stage','Input','Processing','Output'],[('Ingestion','data/source.csv','Spark reads a headered CSV with inferred types.','transactions_df.'),('Transformation','transactions_df','Renames old_name; casts price; derives final_price from base_price plus 18% tax.','transformed_df.'),('Exploration / filtering','transformed_df','Applies the implemented category, status/amount, user, region, and priority conditions.','Displayed filtered result sets.'),('Aggregation','transformed_df','Counts records by category.','category_summary.'),('Storage','Summary and transformed DataFrames','Writes CSV and Parquet output paths.','CSV / Parquet artefacts.'),('Validation','Parquet output','Reads Parquet back into verification_df.','Displayed verification DataFrame.')],[1500,1700,3500,1800])]
q += [h('11. Detailed Methodology')]
for name,what,why,inp,outp in [('Start and load','Creates SparkSession, then reads source.csv.','All subsequent operations use a Spark DataFrame.','CSV source.','transactions_df.'),('Select and initial filter','Selects product_id/price and isolates Electronics.','Checks required fields and category-specific data.','transactions_df.','Displayed selections.'),('Update and derive','Renames legacy name, casts price, calculates final_price.','Creates a clearer schema and tax-inclusive value.','transactions_df.','transformed_df.'),('Business conditions','Filters completed amounts above 1000, non-null users, and North/High records.','Inspects records meeting stated rules.','transformed_df.','Displayed filtered sets.'),('Aggregate/store/validate','Counts categories; writes outputs; reads Parquet back.','Creates persisted results and verifies storage.','transformed_df/category_summary.','CSV/Parquet output and verification_df.')]:q += [h(name,2),t(['What happens','Why required','Input','Output'],[(what,why,inp,outp)],[2600,2700,1600,1900])]
q += [h('12. Implementation'),p('The complete final implementation below is preserved from Assessment_6.ipynb.' )]
for cell in nb['cells']:
 src=''.join(cell.get('source',[]))
 if cell['cell_type']=='markdown' and src.strip().startswith('## Part'):q.append(h(src.strip().splitlines()[0].lstrip('# '),2))
 if cell['cell_type']=='code':q.append(c(src))
q += [h('13. Code Explanation'),t(['Section','Explanation'],[('Spark startup','Creates the Transaction_Pipeline Spark application.'),('Read CSV','Loads the source with header and inferred schema.'),('Field update','Changes old_name to new_name and casts price to double.'),('Calculation','Adds final_price using base_price multiplied by 1.18.'),('Filters','Shows records matching the three independent business-condition rules.'),('Aggregation','Groups transformed transactions by category and counts records.'),('Writes / verification','Persists CSV and Parquet; reopens Parquet to confirm a readable output.')],[2700,5500])]
q += [h('14. Execution Procedure'),p('Open Assessment_6.ipynb in a Python environment with PySpark installed, ensure data/source.csv is available relative to the notebook execution directory, and run cells sequentially. The final cell reads the generated Parquet directory before stopping the Spark session.')]
q += [h('15. Output Screenshots'),p('No separate screenshot image files or saved notebook cell-output images are supplied. The generated files, _SUCCESS markers, and exported PDF artefacts are the available execution evidence; no screenshots are fabricated.')]
q += [h('16. Output Interpretation'),t(['Observed artefact','Interpretation'],[('csv_output/part-...csv','The supplied CSV file contains five transformed detail records, including new_name and final_price.'),('parquet_output/part-...parquet','A detailed Parquet output file is present.'),('_SUCCESS files','Spark completion markers are present for both CSV and Parquet output directories.'),('Parquet read-back code','The final notebook cell reopens output/parquet_output, representing the implemented storage validation step.')],[3000,5400])]
q += [h('17. Results'),t(['Actual observed result','Value / interpretation'],[('Input records','5 source transactions.'),('Category counts','Electronics: 3; Furniture: 1; Clothing: 1.'),('Derived final prices','64,900.00; 14,160.00; 88,500.00; 2,950.00; 17,700.00 for product IDs 101–105 respectively.'),('Completed orders above 1,000','Product IDs 101 and 103.'),('Known-user filter','Four records retain non-null user_id; product ID 103 has missing user_id.'),('CSV detail artefact','Five transformed records are present in the supplied CSV output.'),('Expected behavior','The notebook code writes category_summary to the CSV path and transformed detail to Parquet; the supplied CSV artefact contains transformed detail, so this report distinguishes file evidence from the intended write statement.')],[3100,5400])]
q += [h('18. Analysis')]
for s in ['The 18% tax calculation is consistently represented in the supplied transformed CSV, for example 55,000 becomes 64,900 and 75,000 becomes 88,500.','Electronics is the most frequent category, with three of five transactions.','The high-value completed filter identifies two records; one of them has a missing user identifier, showing that the filters serve different analytical purposes.','Both storage formats have Spark success markers, providing evidence that the output-writing stages completed.']:q.append(b(s))
q += [h('19. Observations'),p('The assignment demonstrates an end-to-end mini Spark lifecycle: local CSV input is read into a DataFrame, transformed and queried, aggregated, stored in CSV/Parquet directories, and validated by reopening the Parquet result.')]
q += [h('20. Challenges and Resolutions'),p('No runtime errors are recorded in the supplied material. The notebook contains the following data-handling and validation steps:'),t(['Condition','Implemented response'],[('Legacy field name','withColumnRenamed changes old_name to new_name.'),('Numeric price requirement','price is cast to double.'),('Missing user IDs','A non-null user filter is available for analyses requiring identified users.'),('Output validation','Parquet is read back after writing.'),('File completion','_SUCCESS markers are present in the supplied output directories.')],[3000,5400])]
q += [h('21. Conclusion'),p('Assessment 6 successfully performs transaction preparation with PySpark. It loads the supplied CSV, standardizes selected fields, derives tax-inclusive prices, applies the required conditions, counts categories, creates CSV and Parquet output paths, and validates the Parquet result through a read-back operation.')]
q += [h('22. Learning Outcomes')]
for s in ['Ingesting a CSV into a Spark DataFrame.','Applying DataFrame selections, filters, renames, casts, and derived columns.','Using aggregate operations to summarise categories.','Writing and validating CSV and Parquet outputs.','Understanding the difference between observed output artefacts and the intended write operations in source code.']:q.append(b(s))
q += [h('23. References')]
for s in ['Assessment_6.ipynb, supplied final notebook.','readme.md, supplied processing sequence.','data/source.csv, supplied transaction dataset.','output/csv_output and output/parquet_output, supplied generated outputs.','Assessment_6.pdf and Assessment_6_merged.pdf, supplied exported notebook artefacts.']:q.append(b(s))
styles=f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="{N}"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:pPr><w:spacing w:after="120" w:line="276"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:keepNext/><w:spacing w:before="280" w:after="140"/><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:b/><w:color w:val="1F4E79"/><w:sz w:val="30"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:pPr><w:keepNext/><w:spacing w:before="220" w:after="100"/><w:outlineLvl w:val="1"/></w:pPr><w:rPr><w:b/><w:color w:val="2F75B5"/><w:sz w:val="25"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Code"><w:name w:val="Code"/><w:pPr><w:spacing w:after="0" w:line="210"/><w:shd w:fill="F3F5F7"/><w:ind w:left="180" w:right="180"/></w:pPr><w:rPr><w:rFonts w:ascii="Consolas" w:hAnsi="Consolas"/><w:sz w:val="16"/></w:rPr></w:style><w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/></w:style></w:styles>'''
doc=f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="{N}" xmlns:r="{R}"><w:body>{''.join(q)}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134" w:header="708" w:footer="708"/><w:headerReference w:type="default" r:id="rId1"/><w:footerReference w:type="default" r:id="rId2"/></w:sectPr></w:body></w:document>'''
head=f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:hdr xmlns:w="{N}"><w:p><w:pPr><w:jc w:val="right"/></w:pPr><w:r><w:rPr><w:color w:val="1F4E79"/><w:sz w:val="18"/></w:rPr><w:t>Data Engineering | Assessment 6</w:t></w:r></w:p></w:hdr>';foot=f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:ftr xmlns:w="{N}"><w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:sz w:val="18"/></w:rPr><w:t>Abhishek Sethi | Page </w:t></w:r><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText>PAGE</w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>1</w:t></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p></w:ftr>'
ct='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>''';rel='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>''';dr='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'''
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
 for n,d in {'[Content_Types].xml':ct,'_rels/.rels':rel,'word/document.xml':doc,'word/styles.xml':styles,'word/header1.xml':head,'word/footer1.xml':foot,'word/_rels/document.xml.rels':dr}.items():z.writestr(n,d.encode())
print(out)
