import os,glob,json,zipfile
from html import escape
r=os.path.dirname(os.path.abspath(__file__));root=os.path.join(r,'delta-lake-assignment');out=os.path.join(r,'Data_Engineering_Assessment_7_Abhishek_Sethi.docx');nb=json.load(open(os.path.join(root,'notebooks','delta_scd_assignment.ipynb'),encoding='utf8'));code='\n\n'.join(''.join(c['source']) for c in nb['cells'] if c['cell_type']=='code')+'\n\n# Standalone validation script\n'+open(os.path.join(root,'verify_delta_merge.py')).read();imgs=glob.glob(os.path.join(root,'screenshots','**','*.png'),recursive=True)
N='http://schemas.openxmlformats.org/wordprocessingml/2006/main';R='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
def x(s):return escape(str(s),quote=False)
def p(s='',st=None):return f'<w:p>{f"<w:pPr><w:pStyle w:val=\"{st}\"/></w:pPr>" if st else ""}<w:r><w:t xml:space="preserve">{x(s)}</w:t></w:r></w:p>'
def h(s):return p(s,'Heading1')
def b(s):return f'<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>{x(s)}</w:t></w:r></w:p>'
def c(s):return ''.join(p(z or ' ','Code') for z in s.splitlines())
def t(a,rows):return '<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/></w:tblPr><w:tr>'+''.join(f'<w:tc><w:tcPr><w:shd w:fill="D9EAF7"/></w:tcPr><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>{x(z)}</w:t></w:r></w:p></w:tc>' for z in a)+'</w:tr>'+''.join('<w:tr>'+''.join(f'<w:tc><w:p><w:r><w:t>{x(z)}</w:t></w:r></w:p></w:tc>' for z in row)+'</w:tr>' for row in rows)+'</w:tbl>'
def pic(i):return f'<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:drawing><wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><wp:extent cx="5200000" cy="2700000"/><wp:docPr id="{i+1}" name="Figure {i+1}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="{i+1}" name="Figure"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rId{i+3}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="5200000" cy="2700000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'
q=[p('DATA ENGINEERING','Title'),p('ASSESSMENT 7','Title'),p('Delta Lake Type 1 SCD Merge Workflow','Title'),t(['Student','Subject'],[('Abhishek Sethi','Data Engineering')]),h('Table of Contents'),p('Update this table in Microsoft Word (References → Update Table) to display page numbers.'),h('1. Assignment Details'),p('A Delta Lake Type 1 slowly changing dimension workflow maintains a Superstore master table from baseline and incremental CSV files.'),h('2. Aim'),p('To ingest, clean, store, merge, and validate incremental Superstore data using Apache Spark and Delta Lake.'),h('3. Problem Statement'),p('A master dataset and an incremental batch must be combined so matched identifiers receive current values and new identifiers are inserted without retaining historical versions.'),h('4. Objectives')]
for s in ['Read baseline and incremental CSV inputs.','Make column names storage-safe and standardize identifier names.','Remove duplicate keys and fill missing city/state values.','Persist an initial Delta table.','Perform a Type 1 Delta MERGE by ID.','Validate final row count and duplicate identifiers.']:q.append(b(s))
q += [h('5. Technologies and Environment'),t(['Area','Actual technology'],[('Language','Python'),('Processing','Apache Spark / PySpark 3.5.0'),('Storage','Delta Lake 3.2.0, local Delta tables'),('Notebook','Jupyter Notebook'),('Dependencies','delta-spark, local Delta Spark and storage JAR files')]),h('6. Dataset/Input Description'),t(['Input','Purpose'],[('Sample - Superstore.csv','Baseline Superstore master records.'),('superstore_incremental.csv','Changed and new records for merge.'),('customer_master.csv / customer_incremental.csv','Inputs used by the separate verification script.')]),h('7. Schema and Data Characteristics'),p('The notebook standardizes the Superstore source into fields such as ID, OrderID, CustomerID, CustomerName, City, State, Sales, and Profit. Delta storage paths include superstore_master and customer_master.'),h('8. Concepts Used')]
for s in ['Delta Lake ACID table storage and transaction logs.','Type 1 slowly changing dimension merge logic.','CSV ingestion and schema normalization.','Deduplication and missing-value completion.','DeltaTable MERGE matched-update and not-matched-insert operations.','Validation through row counts and duplicate-ID checks.']:q.append(b(s))
q += [h('9. Solution Architecture/Workflow'),t(['Stage','Input','Processing','Output'],[('Load','Baseline CSV','Read with header/schema inference.','Raw Spark DataFrame.'),('Clean','Raw data','Safe columns, renamed keys, de-duplicate ID, fill City/State.','Master DataFrame.'),('Store','Clean master','Write Delta format.','Initial Delta table.'),('Merge','Incremental CSV + Delta target','Matched IDs update City/State/Sales/Profit; unseen IDs insert.','Current Type 1 table.'),('Validate','Merged Delta table','Count rows and check duplicate IDs.','Verified final dataset.')]),h('10. Methodology'),p('The implementation loads the baseline Superstore extract, standardizes its columns, removes duplicate IDs, fills missing locations, and writes Delta storage. It loads the incremental batch and executes a Delta MERGE on ID. The final table is displayed and tested for total rows and duplicate IDs. The separate validation script repeats the same Type 1 pattern on customer data.'),h('11. Complete Implementation'),p('Complete final code from the supplied notebook and validation script follows.'),c(code),h('12. Important Code Sections'),t(['Section','Explanation'],[('Spark configuration','Configures local Spark with Delta extension/catalog and supplied JAR dependencies.'),('Master cleaning','Renames identifiers, drops duplicate IDs, fills City/State.'),('Initial Delta write','Stores baseline master in Delta format.'),('MERGE','Updates matched ID values and inserts unmatched records, implementing Type 1 behavior.'),('Validation','Displays final values, counts records, and checks duplicate IDs.')]),h('13. Execution Steps'),c('pip install -r requirements.txt\npython verify_delta_merge.py'),p('Run the notebook cells sequentially from the project environment; the README records expected validation values row_count = 4 and duplicate_ids = 0 for the standalone customer validation.'),h('14. Output Screenshots')]
for i,img in enumerate(imgs):q += [pic(i),p(f'Figure {i+1}: {os.path.relpath(img,root)} — execution evidence for data loading, cleaning, SCD Type 1/2 work, validation, or final output.')]
q += [h('15. Output Explanation'),p('The screenshots provide evidence of data loading, cleaning, SCD processing, validation, and final output. The project README confirms that the Type 1 merge replaces matched customer values and adds new customers.'),h('16. Results'),t(['Observed / expected result','Interpretation'],[('Type 1 merge','Matched records receive latest attributes; unseen identifiers are inserted.'),('Standalone validation expectation','row_count = 4 and duplicate_ids = 0, as stated in README.'),('Delta artefacts','Both customer_master and superstore_master Delta folders include Parquet data files and _delta_log transaction history.')]),h('17. Analysis and Observations'),p('The workflow separates ingestion, cleanup, Delta persistence, incremental merge, and validation. Type 1 behavior keeps current values only, making the final table suitable for current-state reporting rather than historical tracking.'),h('18. Problems Encountered / Solutions Applied'),p('No runtime errors are documented. The implementation handles expected data issues by replacing unsafe column characters, removing duplicate identifiers, filling missing City/State values, and validating duplicates after merge.'),h('19. Conclusion'),p('Assessment 7 successfully demonstrates a local Spark and Delta Lake Type 1 incremental merge pipeline with cleaning, storage, upsert behavior, and quality validation.'),h('20. Learning Outcomes')]
for s in ['Configuring Spark for Delta Lake.','Writing and reading Delta tables.','Using Type 1 SCD merge logic.','Validating merged datasets.','Understanding Delta transaction-log storage.']:q.append(b(s))
q += [h('21. References'),p('README.md, assignment_summary.md, delta_scd_assignment.ipynb, verify_delta_merge.py, supplied input CSV files, requirements.txt, Delta outputs, and supplied screenshots.')]
styles=f'<w:styles xmlns:w="{N}"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:color w:val="1F4E79"/><w:sz w:val="28"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Code"><w:name w:val="Code"/><w:rPr><w:rFonts w:ascii="Consolas"/><w:sz w:val="16"/></w:rPr></w:style><w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/></w:style></w:styles>'
doc=f'<w:document xmlns:w="{N}" xmlns:r="{R}"><w:body>{"".join(q)}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:headerReference w:type="default" r:id="rId1"/><w:footerReference w:type="default" r:id="rId2"/></w:sectPr></w:body></w:document>';head=f'<w:hdr xmlns:w="{N}"><w:p><w:r><w:t>Data Engineering | Assessment 7</w:t></w:r></w:p></w:hdr>';foot=f'<w:ftr xmlns:w="{N}"><w:p><w:r><w:t>Abhishek Sethi | Page </w:t></w:r><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText>PAGE</w:instrText></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p></w:ftr>'
ct='''<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>''';rel='''<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>''';dr=['<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>']+[f'<Relationship Id="rId{i+3}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/i{i}.png"/>' for i in range(len(imgs))]+['</Relationships>']
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
 for n,d in {'[Content_Types].xml':ct,'_rels/.rels':rel,'word/document.xml':doc,'word/styles.xml':styles,'word/header1.xml':head,'word/footer1.xml':foot,'word/_rels/document.xml.rels':''.join(dr)}.items():z.writestr(n,d)
 for i,img in enumerate(imgs):z.write(img,f'word/media/i{i}.png')
print(out)
