import os,glob,zipfile
from html import escape
d=os.path.dirname(os.path.abspath(__file__));o=os.path.join(d,'Apex_Retail_Intelligence_Final_Project_Abhishek_Sethi.docx');files=sorted(glob.glob(os.path.join(d,'0*.py')));code='\n\n'.join('# '+os.path.basename(f)+'\n'+open(f,encoding='utf8').read() for f in files);imgs=glob.glob(os.path.join(d,'screenshots','phase*','*.png'))
N='http://schemas.openxmlformats.org/wordprocessingml/2006/main';R='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
def x(s):return escape(s,quote=False)
def p(s='',st=''):return f'<w:p>{f"<w:pPr><w:pStyle w:val=\"{st}\"/></w:pPr>" if st else ""}<w:r><w:t xml:space="preserve">{x(s)}</w:t></w:r></w:p>'
def h(s):return p(s,'H1')
def c(s):return ''.join(p(z or ' ','Code') for z in s.splitlines())
def pic(i):return f'<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:drawing><wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><wp:extent cx="5200000" cy="2800000"/><wp:docPr id="{i+1}" name="Figure {i+1}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="{i+1}" name="Screenshot"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rId{i+2}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="5200000" cy="2800000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'
def b(s):return f'<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>{x(s)}</w:t></w:r></w:p>'
q=[p('DATA ENGINEERING','Title'),p('APEX RETAIL INTELLIGENCE FINAL PROJECT','Title'),p('Databricks Lakehouse Pipeline and Retail Analytics'),p('Student: Abhishek Sethi'),h('Table of Contents'),p('Update this table in Microsoft Word to display page numbers.'),h('1. Project Overview'),p('A retail analytics lakehouse implemented in Databricks using PySpark, Delta Lake, and Unity Catalog. It processes retail data from Raw through Landing, Bronze, Silver, and Gold layers, then validates the model and publishes KPI-ready tables.'),h('2. Aim'),p('To implement a validated medallion lakehouse pipeline with SCD handling, a Gold star schema, and retail KPI analysis.'),h('3. Objectives')]
for s in ['Preserve incoming CSV files and reconcile landing audit counts.','Create append-only Bronze Delta tables.','Apply Silver data-quality, de-duplication, Type 2 customer, and Type 1 product logic.','Publish Gold dimensions and fact_sales.','Register governed tables through Unity Catalog.','Run end-to-end, idempotency, quality, and compliance validation.']:q.append(b(s))
q += [h('4. Technologies and Environment'),p('Databricks serverless runtime; Python; PySpark; Databricks SQL; Delta Lake; Databricks Volumes; Parquet; Unity Catalog.'),h('5. Architecture and Workflow'),p('CSV source files → Landing Parquet with audit reconciliation → Bronze append-only Delta tables → Silver validated Delta tables with SCD rules → Gold dimensions and fact_sales → KPIs and validation evidence.'),h('6. Layer Design'),p('Raw retains received source batches. Landing converts files to Parquet and performs audit reconciliation. Bronze appends Delta data with ingestion timestamps. Silver validates keys, types, nulls, duplicates, and SCD rules. Gold exposes dim_customer, dim_product, dim_promotion, dim_date, and fact_sales.'),h('7. Implementation'),p('The complete final implementation is preserved below from the four supplied project scripts.'),c(code),h('8. Important Code Sections'),p('01_Raw_Landing_Audit.py organizes raw inputs, writes landing Parquet, reconciles audit counts, and loads Bronze. 02_Silver_Transformation_MERGE_SCD.py applies cleaning, MERGE logic, Type 2 customer history, Type 1 product updates, and surrogate keys. 03_Gold_StarSchema_KPIs.py builds/registers the Gold star schema and KPI outputs. 04_Final_Validation_Testing.py runs end-to-end, idempotency, data-quality, and compliance checks.'),h('9. Execution Procedure'),p('Run the Databricks modules in numerical order. Each stage depends on upstream outputs; run final validation only after Gold tables are available.'),h('10. Outputs and Evidence')]
for i,img in enumerate(imgs):
 q += [pic(i), p(f'Figure {i+1}: {os.path.relpath(img,d)} — supplied execution evidence for the relevant pipeline phase.')]
q += [h('11. Results and Analysis'),p('The supplied project evidence covers landing audits, Bronze Delta loading, Silver merges and SCD behavior, Gold dimensions/fact table creation, KPI outputs, audit-failure tests, duplicate validation, end-to-end validation, idempotency testing, and project completion. The Gold model supports sales by region, promotion AOV, demographic churn, product-quality scoring, and store traffic by hour. Where cost is unavailable, regional sales is used as the implemented proxy for margin-oriented reporting.'),h('12. Challenges and Solutions'),p('The project enforces controls for audit total mismatches, duplicate business keys, null primary keys, type/range conformance, surrogate-key uniqueness, and Gold foreign-key relationships. Validation deliberately tests failure scenarios and repeatability.'),h('13. Conclusion'),p('The completed project delivers a governed retail lakehouse from raw CSV to validated Gold analytics tables using Delta Lake, SCD handling, star-schema modelling, KPI logic, and repeatable validation.'),h('14. Learning Outcomes')]
for s in ['Medallion lakehouse architecture.','Delta Lake ingestion and MERGE processing.','SCD Type 1 and Type 2 implementation.','Gold star-schema design.','Unity Catalog governance.','Data quality, audit, and idempotency testing.','Retail KPI analysis.']:q.append(b(s))
q += [h('15. References'),p('README.md; the four supplied Python pipeline modules; Images.md; supplied screenshots; Celebal Architecture.png; and Apex_Retail_Intelligence_Final_Project_Report.pdf.')]
sty=f'<w:styles xmlns:w="{N}"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="H1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Code"><w:name w:val="Code"/><w:rPr><w:rFonts w:ascii="Consolas"/><w:sz w:val="14"/></w:rPr></w:style></w:styles>'
doc=f'<w:document xmlns:w="{N}" xmlns:r="{R}"><w:body>{"".join(q)}<w:sectPr/></w:body></w:document>';ct='''<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>''';rel='''<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>''';dr='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'+''.join(f'<Relationship Id="rId{i+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image{i+1}.png"/>' for i in range(len(imgs)))+'</Relationships>'
with zipfile.ZipFile(o,'w') as z:
 for n,v in {'[Content_Types].xml':ct,'_rels/.rels':rel,'word/document.xml':doc,'word/styles.xml':sty,'word/_rels/document.xml.rels':dr}.items():z.writestr(n,v)
 for i,img in enumerate(imgs):z.write(img,f'word/media/image{i+1}.png')
print(o)
